name: pre-commit

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  pre-commit:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_build_env
        with:
          python-version: 3.13
          run-uv-sync: true
      - run: uv run pre-commit run --all-files --show-diff-on-failure
        env:
          SKIP: update-pyi-files
